language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  - composer self-update
  - composer global require codeclimate/php-test-reporter
  - composer install

before_script:
  - mysql -e 'create database yii2_many_to_many;'

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - ~/.composer/vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"